# Generated by Django 3.1.12 on 2025-01-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('published_date', models.DateField(verbose_name='Fecha de Publicación')),
                ('genre', models.CharField(choices=[('FIC', 'Ficción'), ('NOF', 'No Ficción'), ('SCI', 'Ciencia'), ('ROM', 'Romance'), ('MIS', 'Misterio'), ('FAN', 'Fantasía')], max_length=3, verbose_name='Género')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-created_at'],
            },
        ),
    ]
